default_agent: ai_support_agent
agents:
  ai_support_agent:
    name: ai_support_agent
    language: python
    node_version: '20'
    entrypoint: C:/Users/nene1/Documents/ai-support-agent/starter/main.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: none
    source_path: C:\Users\nene1\Documents\ai-support-agent\starter
    aws:
      execution_role: arn:aws:iam::445416043663:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-3b4f816c88
      execution_role_auto_create: false
      account: '445416043663'
      region: us-east-1
      ecr_repository: 445416043663.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-ai_support_agent
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: ai_support_agent-m8R0OvF6m6
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:445416043663:runtime/ai_support_agent-m8R0OvF6m6
      agent_session_id: 168f43e0-e66e-460a-b60a-a58e018e94da
    codebuild:
      project_name: bedrock-agentcore-ai_support_agent-builder
      execution_role: arn:aws:iam::445416043663:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-3b4f816c88
      source_bucket: bedrock-agentcore-codebuild-sources-445416043663-us-east-1
    memory:
      mode: STM_AND_LTM
      memory_id: CustomerSupportMemory-dg74yK9va0
      memory_arn: null
      memory_name: ai_support_agent_memory
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
